# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('idEscuela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('idGrupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('idLeccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Leccion',
            },
        ),
        migrations.CreateModel(
            name='Puntuaciones',
            fields=[
                ('idPuntuacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(blank=True)),
                ('idLeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Leccion')),
            ],
            options={
                'db_table': 'Puntuaciones',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipoUsuario', models.BooleanField()),
                ('nombre', models.CharField(max_length=100)),
                ('idUser', models.IntegerField(unique=True)),
                ('idEscuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Escuelas')),
                ('idGrupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.Grupos')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='puntuaciones',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
        ),
    ]
