# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuaciones',
            name='idLeccion',
            field=models.ForeignKey(db_column='idLeccion', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Leccion'),
        ),
        migrations.AlterField(
            model_name='puntuaciones',
            name='idUsuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idEscuela',
            field=models.ForeignKey(db_column='idEscuela', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Escuelas'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idGrupo',
            field=models.ForeignKey(db_column='idGrupo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.Grupos'),
        ),
    ]
