# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20170820_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
